using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using DemaciaRisingSim.Core;

namespace DemaciaRisingSim.UI;

/// <summary>
/// ViewModel for a single settlement row displayed in the board grid.
/// </summary>
public class SettlementViewModel : INotifyPropertyChanged
{
    private string _structures = string.Empty;
    private int _lumber;
    private int _stone;
    private int _metal;
    private int _petricite;
    private int _food;

    public string SettlementName { get; set; } = string.Empty;
    public string Environment { get; set; } = string.Empty;

    public string Structures
    {
        get => _structures;
        set { _structures = value; OnPropertyChanged(); }
    }

    public int Lumber
    {
        get => _lumber;
        set { _lumber = value; OnPropertyChanged(); }
    }

    public int Stone
    {
        get => _stone;
        set { _stone = value; OnPropertyChanged(); }
    }

    public int Metal
    {
        get => _metal;
        set { _metal = value; OnPropertyChanged(); }
    }

    public int Petricite
    {
        get => _petricite;
        set { _petricite = value; OnPropertyChanged(); }
    }

    public int Food
    {
        get => _food;
        set { _food = value; OnPropertyChanged(); }
    }

    public event PropertyChangedEventHandler? PropertyChanged;

    protected void OnPropertyChanged([CallerMemberName] string? name = null)
        => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
}

/// <summary>
/// Main ViewModel driving the board visualization, simulation controls, and settings.
/// Settings are persisted between application sessions via <see cref="SettingsService"/>.
/// Commands are exposed as <c>IRelayCommand</c> / <c>IAsyncRelayCommand</c> properties
/// generated by the CommunityToolkit.Mvvm source generator so no code-behind click
/// handlers are needed.
/// </summary>
public partial class MainViewModel : ObservableObject
{
    // ── Display / output properties (not persisted) ───────────────────────────
    [ObservableProperty] private string _totalLumber    = "0";
    [ObservableProperty] private string _totalStone     = "0";
    [ObservableProperty] private string _totalMetal     = "0";
    [ObservableProperty] private string _totalPetricite = "0";
    [ObservableProperty] private string _totalFood      = "0";
    [ObservableProperty] private string _turnsLumber    = "—";
    [ObservableProperty] private string _turnsStone     = "—";
    [ObservableProperty] private string _turnsMetal     = "—";
    [ObservableProperty] private string _turnsPetricite = "—";
    [ObservableProperty] private string _maxTurns       = "—";
    [ObservableProperty] private string _statusMessage  =
        "Ready. Click 'Load Default Board' to initialize the board, or 'Optimize' to find the best layout.";
    [ObservableProperty] private bool _isBusy;
    [ObservableProperty] private string _iterationsSummary = string.Empty;

    // ── Settings (persisted) ──────────────────────────────────────────────────
    [ObservableProperty] private bool _requireDurandsWorkshop    = true;
    [ObservableProperty] private bool _requireShrineOfVeiledLady = true;
    [ObservableProperty] private bool _requireQuartermaster      = true;
    [ObservableProperty] private int  _maxBuildingLevel          = 4;
    [ObservableProperty] private int  _foodTargetPerSettlement   = 2;
    [ObservableProperty] private int  _lumberTarget              = 296_300;
    [ObservableProperty] private int  _stoneTarget               = 343_400;
    [ObservableProperty] private int  _metalTarget               = 143_650;
    [ObservableProperty] private int  _petriciteTarget           = 1_450;

    private Dictionary<string, Settlement> _board;

    public ObservableCollection<SettlementViewModel> Settlements { get; } = [];

    // ── Construction ─────────────────────────────────────────────────────────

    public MainViewModel()
    {
        // Load persisted settings and initialise backing fields directly so the
        // OnXxxChanged callbacks (which call SaveSettings) are not triggered during
        // construction — nothing to save yet since we're loading from disk.
        var s = SettingsService.Load();
        _requireDurandsWorkshop    = s.RequireDurandsWorkshop;
        _requireShrineOfVeiledLady = s.RequireShrineOfVeiledLady;
        _requireQuartermaster      = s.RequireQuartermaster;
        _maxBuildingLevel          = s.MaxBuildingLevel;
        _foodTargetPerSettlement   = s.FoodTargetPerSettlement;
        _lumberTarget              = s.LumberTarget;
        _stoneTarget               = s.StoneTarget;
        _metalTarget               = s.MetalTarget;
        _petriciteTarget           = s.PetriciteTarget;

        _board = BoardData.CreateDefaultBoard();
        LoadBoard(_board);
    }

    // ── Commands (generated by [RelayCommand] source generator) ──────────────

    /// <summary>Copies the solver iterations summary to the clipboard.</summary>
    [RelayCommand]
    private void CopyIterationsSummary()
    {
        if (!string.IsNullOrEmpty(IterationsSummary))
            System.Windows.Clipboard.SetText(IterationsSummary);
    }

    /// <summary>Loads and displays the default board without optimization.</summary>
    [RelayCommand]
    private void LoadDefault()
    {
        _board = BoardData.CreateDefaultBoard();
        LoadBoard(_board);
        StatusMessage = "Default board loaded (all Lumberyard level 1).";
    }

    /// <summary>
    /// Runs the optimizer on the current board asynchronously and refreshes the display.
    /// The generated <c>OptimizeCommand</c> (IAsyncRelayCommand) automatically disables
    /// itself while the task is running, preventing re-entrant clicks.
    /// </summary>
    [RelayCommand]
    private async Task OptimizeAsync()
    {
        IsBusy = true;
        StatusMessage = "Optimizing board layout…";
        IterationsSummary = string.Empty;

        // Capture the UI synchronization context so callbacks from the background thread
        // can update StatusMessage.  SynchronizationContext.Current is non-null for any
        // command invoked from the WPF UI thread; the null guard handles edge cases.
        var uiContext = SynchronizationContext.Current;

        Action<string> progressCallback = msg =>
        {
            // Send is synchronous: the background thread waits until the UI thread has
            // processed the update, so no queued callbacks can overwrite the final message.
            uiContext?.Send(_ => StatusMessage = msg, null);
        };

        try
        {
            var settings = BuildSimulationSettings();
            var boardToOptimize = BoardData.Clone(_board);
            var result = await Task.Run(() =>
                Simulator.OptimizeBoard(boardToOptimize, settings, progressCallback));
            _board = result.Board;
            LoadBoard(_board, settings);
            var turns = Simulator.TurnsToComplete(Simulator.BoardOutput(_board), settings);
            StatusMessage = $"Optimization complete. Max turns to complete: {TurnsBreakdown.Format(turns.Max)}";
            IterationsSummary = result.Phases.Count > 0
                ? string.Join("  |  ", result.Phases.Select(p =>
                    $"Phase {p.Phase} ({p.Description}): {p.Passes} pass(es)."))
                : string.Empty;
        }
        finally
        {
            IsBusy = false;
        }
    }

    // ── Settings persistence callbacks ────────────────────────────────────────
    // Called by the [ObservableProperty] source generator after each settings property changes.

    partial void OnRequireDurandsWorkshopChanged(bool value)    => SaveSettings();
    partial void OnRequireShrineOfVeiledLadyChanged(bool value) => SaveSettings();
    partial void OnRequireQuartermasterChanged(bool value)      => SaveSettings();
    partial void OnMaxBuildingLevelChanged(int value)           => SaveSettings();

    // Integer settings are clamped to ≥ 0.  When a negative value is set the property is
    // immediately corrected to 0, which re-fires the callback with the clamped value and
    // then calls SaveSettings().  The recursion terminates after at most one extra level
    // because the second invocation always satisfies value >= 0.
    partial void OnFoodTargetPerSettlementChanged(int value)
        => ClampNonNegativeAndSave(value, v => FoodTargetPerSettlement = v);
    partial void OnLumberTargetChanged(int value)
        => ClampNonNegativeAndSave(value, v => LumberTarget = v);
    partial void OnStoneTargetChanged(int value)
        => ClampNonNegativeAndSave(value, v => StoneTarget = v);
    partial void OnMetalTargetChanged(int value)
        => ClampNonNegativeAndSave(value, v => MetalTarget = v);
    partial void OnPetriciteTargetChanged(int value)
        => ClampNonNegativeAndSave(value, v => PetriciteTarget = v);

    /// <summary>
    /// Clamps <paramref name="value"/> to zero when negative, or calls
    /// <see cref="SaveSettings"/> when the value is already valid.
    /// Extracted to avoid duplicating this logic across all integer settings handlers.
    /// </summary>
    private void ClampNonNegativeAndSave(int value, Action<int> setter)
    {
        if (value < 0) setter(0);
        else SaveSettings();
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    private SimulationSettings BuildSimulationSettings() => new()
    {
        RequireDurandsWorkshop    = RequireDurandsWorkshop,
        RequireShrineOfVeiledLady = RequireShrineOfVeiledLady,
        RequireQuartermaster      = RequireQuartermaster,
        MaxBuildingLevel          = MaxBuildingLevel,
        FoodTargetPerSettlement   = FoodTargetPerSettlement,
        LumberTarget              = LumberTarget,
        StoneTarget               = StoneTarget,
        MetalTarget               = MetalTarget,
        PetriciteTarget           = PetriciteTarget,
    };

    private void SaveSettings() =>
        SettingsService.Save(new AppSettings
        {
            RequireDurandsWorkshop    = RequireDurandsWorkshop,
            RequireShrineOfVeiledLady = RequireShrineOfVeiledLady,
            RequireQuartermaster      = RequireQuartermaster,
            MaxBuildingLevel          = MaxBuildingLevel,
            FoodTargetPerSettlement   = FoodTargetPerSettlement,
            LumberTarget              = LumberTarget,
            StoneTarget               = StoneTarget,
            MetalTarget               = MetalTarget,
            PetriciteTarget           = PetriciteTarget,
        });

    private void LoadBoard(Dictionary<string, Settlement> board, SimulationSettings? settings = null)
    {
        Settlements.Clear();

        foreach (var kv in board)
        {
            var settlement = kv.Value;
            var output = Simulator.SettlementOutput(settlement);

            Settlements.Add(new SettlementViewModel
            {
                SettlementName = settlement.Name,
                Environment    = settlement.Environment.ToString(),
                Structures     = string.Join(", ", settlement.Structures.Select(s => s.ToString())),
                Lumber         = output.Lumber,
                Stone          = output.Stone,
                Metal          = output.Metal,
                Petricite      = output.Petricite,
                Food           = output.Food,
            });
        }

        UpdateTotals(board, settings);
    }

    private void UpdateTotals(Dictionary<string, Settlement> board, SimulationSettings? settings = null)
    {
        settings ??= BuildSimulationSettings();

        var total = Simulator.BoardOutput(board);
        TotalLumber    = total.Lumber.ToString();
        TotalStone     = total.Stone.ToString();
        TotalMetal     = total.Metal.ToString();
        TotalPetricite = total.Petricite.ToString();
        TotalFood      = total.Food.ToString();

        var turns = Simulator.TurnsToComplete(total, settings);
        TurnsLumber    = TurnsBreakdown.Format(turns.Lumber);
        TurnsStone     = TurnsBreakdown.Format(turns.Stone);
        TurnsMetal     = TurnsBreakdown.Format(turns.Metal);
        TurnsPetricite = TurnsBreakdown.Format(turns.Petricite);
        MaxTurns       = TurnsBreakdown.Format(turns.Max);
    }
}
